### ISSUE TITLE
fonts sizes are still weird with --markup 

### ISSUE THREAD

**Issue by janhn** [dov/paps#15]
The default font is not applied when using --markup. Trying input such as the below with and without the --markup option the result with markup seems off not by just font size.

markup.txt:
<div>
Markup default font
&#x3C;span foreground=&#x22;blue&#x22;&#x3E;Markup blue&#x3C;/span&#x3E;
&#x3C;span font=&#x22;Monospace 12&#x22;&#x3E;Monospace 12&#x3C;/span&#x3E;
</div>

**Comment by dov** [comment]
Fixed (hopefully) in 13490da .
