### ISSUE TITLE
Printing two-sided is hardcoded in output PostScript files.

### ISSUE THREAD

**Issue by osayama** [dov/paps#20]
In 20151223 version of paps, I got the following issue.

There is an issue with physically printing PostScript files one-sided or
two-sided. It seems to me that currently this information is hard-coded in
PostScript documents generated by paps - I was not able to configure this in
the print dialog.
The problematic part in all output ps files from paps seems to be this one:

%%BeginSetup
%%IncludeFeature: *Duplex DuplexTumble
%%EndSetup

Right now, all the documents are printed two-sided, short edge. After
removing the IncludeFeature line, I was able to configure the print
preferences as I wanted to.

We are applying the following patch so it would be great if this
is also applied by default.

gdiff -u paps.c.org paps.c
--- paps.c.org        2016-07-20 09:21:33.529764313 +0900
+++ paps.c      2016-07-20 10:41:12.232506530 +0900
@@ -678,16 +678,16 @@
       page_width = page_height;
       page_height = tmp;
       if (do_tumble < 0)
-        do_tumble = TRUE;
+        do_tumble = FALSE;
       if (do_duplex < 0)
-        do_duplex = TRUE;
+        do_duplex = FALSE;
     }
   else
     {
       if (do_tumble < 0)
-        do_tumble = TRUE;
+        do_tumble = FALSE;
       if (do_duplex < 0)
-        do_duplex = TRUE;
+        do_duplex = FALSE;
     }

**Comment by dov** [comment]
Sorry for the long delay in referencing this. Would you mind providing a pull request, or at least clean up the garbled markdown of the patch?

**Comment by osayama** [comment]
Thank you for your reply. Yes, I tried to create a pull request.
