### ISSUE TITLE
paps dumps core with --columns=0 option

### ISSUE THREAD

**Issue by osayama** [dov/paps#21]
I got the report that paps dumps core with --columns=0 option.
To reproduce,

echo "Something" | paps --columns=0

% echo "Something" | ./paps --columns=0
zsh: done                                    echo "Something" | 
zsh: floating point exception (core dumped)  ./paps --columns=0

We are applying the following patch so it would be great if this
is also applied by default.

% gdiff -u paps.c.org paps.c
--- paps.c.org  2016-07-20 09:21:33.529764313 +0900
+++ paps.c      2016-07-20 11:15:21.514121049 +0900
@@ -667,6 +667,11 @@
   glyph_font_size = pango_font_description_get_size(font_description) / PANGO_S
CALE;
   pango_context_set_font_description (pango_context, font_description);

\+  if (num_columns == 0) {
+    fprintf(stderr, _("%s: Invalid input: --columns=%d, using default.\n"), g_
get_prgname (), num_columns);
+    num_columns = 1;
+  }
+
   if (num_columns == 1)
     total_gutter_width = 0;
   else

**Comment by dov** [comment]
No problem. Please provide a pull request. I would also do <= 0 test for the columns.

**Comment by janhn** [comment]
This should be fixed now. Thanks for the merge.
