### ISSUE TITLE
cpi option forces printing line breaks anywhere

### ISSUE THREAD

**Issue by osayama** [dov/paps#28]
In 20151223 version of paps, I got the following bug report.

After using --cpi option, the output of paps looks as if --wrap=char option
was used. Line breaks are inserted even in the middle of words. This cannot
be overwritten even by using --wrap=word option.
According to man page, cpi should be an alternative way to specify font size.
The font size is changed, but line breaking behavior is different.

To reproduce this issue, use any English text as input to following command:

% LANG=C
% man paps | col -xb | paps --cpi=8 > out.ps

If I see this out.ps through ghostscript, I can see line breaking in the 
middle of words. Ex, the word "creating" is wrapped between "cre" and "ating".

**Comment by dov** [comment]
I can't reproduce this. Please test with the latest paps from source.
