### ISSUE TITLE
Meson based build doesn't deliver paps.1 man page

### ISSUE THREAD

**Issue by l1gi** [dov/paps#38]
Hi,

as far as I understand there is no info in meson.build files how to deliver paps.1 man page. Could you confirm that?

I am updating paps to the newest version, switched to meson and I dont't see paps.1 in the proto area.

Thank you

**Comment by dov** [comment]
Thanks. Indeed you are correct. meson is quite a late addition, and I never completed it fully. Feel free to send me a PR!

**Comment by l1gi** [comment]
https://github.com/dov/paps/pull/39

Thank you.
