### ISSUE TITLE
error: cannot recognize version marker

### ISSUE THREAD

**Issue by gnusupport** [dov/paps#44]
I get this error:

```
$ mupdf Friday-June-24-2022-07\:51\:12.pdf 
error: cannot recognize version marker
warning: trying to repair broken xref
warning: repairing PDF document
```

PDF was generated with options: "--format" "--landscape" "--title" "--header"

I hope this may be repaired as Emacs cannot read these files.

**Comment by dov** [comment]
Sorry. I can't replicate this on my Fedora system with the latest paps sources. Note that paps is fully relying on cairo for its pdf output, so there might be something else that is not working on your system. If you would like to help track this down it would help if you could you try following  the example at https://zetcode.com/gfx/cairo/cairobackends/ and try to generate a pdf file. Does it work?

**Comment by gnusupport** [comment]
I did not use program, but command line paps tool.

**Comment by gnusupport** [comment]
```
$ echo hello | paps > new.pdf
~
$ mupdf new.pdf 
error: cannot recognize version marker
warning: trying to repair broken xref
warning: repairing PDF document
error: no objects found
mupdf: error: cannot open document
~
$ evince new.pdf 
```

mupdf cannot even open file generated this way, but Evince opens it and I see "Hello"

**Comment by gnusupport** [comment]
I have just tried it on different distribution, on the Debian latest, and pdfinfo gives me same errors.

**Comment by dov** [comment]
The default output format of paps is postscript and I get the same errors if I try mupdf as well as pdfinfo on the postscript file produced by `echo hello | paps > new.pdf`.

However if I do `echo hello | paps --format pdf > new1.pdf` the following both mupdf and pdfinfo work on the pdf file without errors on my Fedora system.

**Comment by gnusupport** [comment]
I was under impression I used "format" in my Emacs function, however, now I am confused and this bug deserves to be closed. 👀

```
(defun rcd-command-output-from-input (program input &rest args)
  "Return output string from PROGRAM with given INPUT string and optional ARGS."
  (let* ((output (with-temp-buffer
		   (insert input)
		   (apply #'call-process-region nil nil program t t nil args)
		   (buffer-string))))
    output))

(defun rcd-paps-process (text &optional format title &rest args)
  (let* ((format (or format "pdf"))
	 (title (or title (buffer-name)))
	 (length (length title))
	 (max 45)
	 (title (if (> length max) (substring title 0 max) title)))
    (apply 'rcd-command-output-from-input "paps" text "--format" format "--landscape" "--title" title "--header" args)))

(defun rcd-paps-buffer-to-pdf-view ()
  (interactive)
  (let ((output (rcd-paps-process-buffer))
	(file-name (rcd-temp-file-name nil "pdf")))
    (hyperscope-evince (string-to-file-force output file-name))))
```
