### ISSUE TITLE
Observing spacing on top and bottom of letters, can't make box tables

### ISSUE THREAD

**Issue by gnusupport** [dov/paps#47]
I observe the problem of spacing on top and bottom of letters.

See picture: https://gnu.support/images/tmp/2023-01-04/2023-01-04-10:56:51.png

The box lines do not get connected due to spacing.

How to reproduce? Put the below box into file and try creating PDF.

```
╔═══╦═══╦═══╗
║ 1 ║ 2 ║ 3 ║
╠═══╬═══╬═══╣
║ A ║ B ║ C ║
╚═══╩═══╩═══╝
```

**Comment by gnusupport** [comment]
I use following:

```
("--footer-center=Page {page_idx:02d} of {num_pages:02d} of translation" "--gutter-width=40" "--left-margin=36" "--right-margin=36" "--top-margin=36" "--bottom-margin=36" "--gravity-hint=natural" "--gravity=auto" "--footer" "--paper=a4" "--font=Monospace 12" "--columns=1" "--landscape" "--format=pdf")
```

**Comment by dov** [comment]
I tried reproducing this, but failed, neither with paps nor with pango-view. I think you have a font problem. Try using a "real font", like "DejaVu Sans Mono" and see if it solves the problem.

**Comment by gnusupport** [comment]
It is solved as that font works..
