### ISSUE TITLE
Cannot run ./configure in /src dir

### ISSUE THREAD

**Issue by levimaaia** [dov/paps#51]
Following the instructions in INSTALL, I 'cd' to paps/src and entered the command 

`./configure && make && make install`

That returned the error 

`-bash: ./configure: No such file or directory`

Using a Raspbian GNU/Linux 11 (bullseye).

I used apt-get to install it originally but the most recent version they seem to have at apt-get is 0.6.8-7.1

**Comment by dov** [comment]
The instructions in install do not say to enter paps/src before running configure. You should run configure (like in all autogen projects) from the top directory.

Note that you should use the tarball paps-0.7.9.tar.gz for the instructions to be valid. To run from git you should use autogen.sh in the top directory. I should perhaps add a file "Develop" to explain that.

**Comment by levimaaia** [comment]
I am a bit of a novice with compiling from source and I can't get it to work. Originally, I installed it using `apt-get` but I am running into the blank page bug that the current version fixes. Is there a way to install 0.7.9 using `apt-get`?
