### ISSUE TITLE
Separate processing messages from standard output

### ISSUE THREAD

**Issue by gnusupport** [dov/paps#53]
I am observing that I will get the line `Got 1 pages` if I redirect output to PDF like following:
```
$ paps --markup my-pango.txt > my-pango.pdf
```
And such PDF file is invalid and cannot be opened.

If I however, do it this way, then it will work:
```
$ paps --markup my-pango.txt -o my-pango.pdf
```

It is necessary to separate processing messages from standard output. Please consider separating processing messages maybe to be printed to standard error, instead of to standard output. As in that case, the output by redirection would work, and message would be shown to user, and not go into PDF file.

In that case user would need to do something like following to get the same error:
```
$ paps --markup my-pango.txt > my-pango.pdf 2>&1
```
As that would be explicit, it would tell to program to put even error messages to file.

**Comment by dov** [comment]
This has been fixed in HEAD. Please confirm that it is working and I will release version 0.8.0.

**Comment by gnusupport** [comment]
I confirm that it works well now.
