### ISSUE TITLE
Cannot build on ArchLinux

### ISSUE THREAD

**Issue by hutou** [dov/paps#67]
Hi,
Compilation is Ok with `meson`, but `./configure && make` does not work

hubert@xps15al:~/abs/paps-0.8.0 $ LANG=C make
make  all-recursive
make[1]: Entering directory '/home/hubert/abs/paps-0.8.0'
Making all in src
make[2]: Entering directory '/home/hubert/abs/paps-0.8.0/src'
g++ -DHAVE_CONFIG_H -I. -I..  -DGETTEXT_PACKAGE='"paps"' -DDATADIR='"/usr/local/share"'  -fno-strict-aliasing -Wnested-externs -Wmissing-prototypes -Wstrict-prototypes -Wdeclaration-after-statement -Wimplicit-function-declaration -Wold-style-definition -Wjump-misses-init -Wall -Wextra -Wundef -Wwrite-strings -Wpointer-arith -Wmissing-declarations -Wredundant-decls -Wno-unused-parameter -Wno-missing-field-initializers -Wformat=2 -Wcast-align -Wformat-nonliteral -Wformat-security -Wsign-compare -Wstrict-aliasing -Wshadow -Winline -Wpacked -Wmissing-format-attribute -Wmissing-noreturn -Winit-self -Wmissing-include-dirs -Wunused-but-set-variable -Warray-bounds -Wreturn-type -Wswitch-enum -Wswitch-default -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wrestrict -Wnull-dereference -Wdouble-promotion -Werror -Wno-suggest-attribute=format -Wno-error=unused-parameter -Wno-error=missing-field-initializers -Wno-format-y2k -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/pixman-1 -I/usr/include/libpng16 -I/usr/include/sysprof-6 -pthread  -g -O2 -MT paps-paps.o -MD -MP -MF .deps/paps-paps.Tpo -c -o paps-paps.o `test -f 'paps.cc' || echo './'`paps.cc
cc1plus: warning: command-line option '-Wnested-externs' is valid for C/ObjC but not for C++
cc1plus: warning: command-line option '-Wmissing-prototypes' is valid for C/ObjC but not for C++
cc1plus: warning: command-line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
cc1plus: warning: command-line option '-Wdeclaration-after-statement' is valid for C/ObjC but not for C++
cc1plus: warning: command-line option '-Wimplicit-function-declaration' is valid for C/ObjC but not for C++
cc1plus: warning: command-line option '-Wold-style-definition' is valid for C/ObjC but not for C++
cc1plus: warning: command-line option '-Wjump-misses-init' is valid for C/ObjC but not for C++
In file included from /usr/include/glib-2.0/glib/giochannel.h:36,
                 from /usr/include/glib-2.0/glib.h:56,
                 from /usr/include/glib-2.0/glib/gprintf.h:23,
                 from /usr/include/glib-2.0/glib/gstdio.h:24,
                 from paps.cc:23:
paps.cc: In function 'bool copy_pango_parse_enum(GType, const char*, int*, bool, char**)':
/usr/include/glib-2.0/glib/gstring.h:73:31: error: ignoring return value of 'gchar* g_string_free_and_steal(GString*)' declared with attribute 'warn_unused_result' [-Werror=unused-result]
   73 |       g_string_free_and_steal (str))            \
      |       ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
paps.cc:388:11: note: in expansion of macro 'g_string_free'
  388 |           g_string_free (s, possible_values ? false : true);
      |           ^~~~~~~~~~~~~
paps.cc: In function 'char* read_file(FILE*, gchar*)':
/usr/include/glib-2.0/glib/gstring.h:73:31: error: ignoring return value of 'gchar* g_string_free_and_steal(GString*)' declared with attribute 'warn_unused_result' [-Werror=unused-result]
   73 |       g_string_free_and_steal (str))            \
      |       ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
paps.cc:1047:3: note: in expansion of macro 'g_string_free'
 1047 |   g_string_free (inbuf, false);
      |   ^~~~~~~~~~~~~
paps.cc: In function 'std::string get_date()':
/usr/include/glib-2.0/glib/gstring.h:73:31: error: ignoring return value of 'gchar* g_string_free_and_steal(GString*)' declared with attribute 'warn_unused_result' [-Werror=unused-result]
   73 |       g_string_free_and_steal (str))            \
      |       ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
paps.cc:1674:7: note: in expansion of macro 'g_string_free'
 1674 |       g_string_free(inbuf, false);
      |       ^~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gstring.h:73:31: error: ignoring return value of 'gchar* g_string_free_and_steal(GString*)' declared with attribute 'warn_unused_result' [-Werror=unused-result]
   73 |       g_string_free_and_steal (str))            \
      |       ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
paps.cc:1683:5: note: in expansion of macro 'g_string_free'
 1683 |     g_string_free(inbuf, false);
      |     ^~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [Makefile:454: paps-paps.o] Error 1
make[2]: Leaving directory '/home/hubert/abs/paps-0.8.0/src'
make[1]: *** [Makefile:502: all-recursive] Error 1
make[1]: Leaving directory '/home/hubert/abs/paps-0.8.0'
make: *** [Makefile:387: all] Error 2

**Comment by dov** [comment]
Thanks for the report. If meson works, then it is good enough. As I wrote in the INSTALL.md, the prefered build environment is meson. But I'll be happy to receive a patch.
